# Generated by Django 6.0.7 on 2026-07-16 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('core', '0001_initial'),
        ('premissas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovado', 'Aprovado')], default='rascunho', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conjunto_premissas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='premissas.conjuntopremissas')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organizacao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('S', 'Simples'), ('A', 'Intermediária'), ('B', 'Completa'), ('C', 'Grande porte'), ('D', 'Reforma')], max_length=1)),
                ('hh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status_execucao', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('reprogramada', 'Reprogramada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_preventiva', to='cadastro.ativo')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_preventiva', to='cadastro.oficina')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organizacao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_preventiva', to='cadastro.pessoa')),
                ('plano_anual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='plano.planoanual')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
