# Generated by Django 6.0.7 on 2026-07-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopreventiva',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Numero de cruzamentos de gatilho agregados nesta semana/evento.'),
        ),
    ]
