# Generated by Django 6.0.7 on 2026-07-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0002_eventopreventiva_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoanual',
            name='hh_prev_por_oficina',
            field=models.JSONField(default=dict, help_text="Saida de apps.motor.plano.calc_plan_prev: {oficina: [12 floats]}. Persistido porque depende da simulacao semanal completa da frota (apps.motor.cronograma) — recalculado apenas em apps/plano/services.py, nunca a partir dos EventoPreventiva individuais (que guardam so a 'oficina principal' de cada evento, nao o rateio entre oficinas)."),
        ),
    ]
