# Generated by Django 6.0.7 on 2026-07-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='tipo_gatilho',
            field=models.CharField(choices=[('Horas', 'Horas'), ('KM', 'Quilômetros')], max_length=10),
        ),
        migrations.AlterField(
            model_name='classeativo',
            name='unidade',
            field=models.CharField(choices=[('Horas', 'Horas'), ('KM', 'Quilômetros')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalativo',
            name='tipo_gatilho',
            field=models.CharField(choices=[('Horas', 'Horas'), ('KM', 'Quilômetros')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalclasseativo',
            name='unidade',
            field=models.CharField(choices=[('Horas', 'Horas'), ('KM', 'Quilômetros')], max_length=10),
        ),
    ]
