# Generated by Django 6.0.7 on 2026-07-17 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_ativo_tipo_gatilho_alter_classeativo_unidade_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistatividade',
            options={'ordering': ['id_checklist', 'seq'], 'verbose_name': 'Atividade de checklist', 'verbose_name_plural': 'Atividades de checklist'},
        ),
        migrations.AddField(
            model_name='ativo',
            name='carregado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='id_externo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='oficina',
            field=models.ForeignKey(blank=True, help_text='Oficina responsável (informativo — o motor apura a oficina por evento via checklist).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos', to='cadastro.oficina'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='origem_arquivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ativo',
            name='placa_serie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ativo',
            name='subclasse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ativo',
            name='tipo_preventiva_atual',
            field=models.CharField(blank=True, choices=[('S', 'Simples'), ('A', 'Intermediária'), ('B', 'Completa'), ('C', 'Grande porte'), ('D', 'Reforma')], max_length=1),
        ),
        migrations.AddField(
            model_name='ativo',
            name='ultima_prev_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='ultima_prev_medicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='checklistatividade',
            name='carregado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistatividade',
            name='id_checklist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='checklistatividade',
            name='id_externo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklistatividade',
            name='nome_checklist',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='checklistatividade',
            name='origem_arquivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='checklistatividade',
            name='seq',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalativo',
            name='carregado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalativo',
            name='id_externo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalativo',
            name='oficina',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Oficina responsável (informativo — o motor apura a oficina por evento via checklist).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastro.oficina'),
        ),
        migrations.AddField(
            model_name='historicalativo',
            name='origem_arquivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='historicalativo',
            name='placa_serie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalativo',
            name='subclasse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalativo',
            name='tipo_preventiva_atual',
            field=models.CharField(blank=True, choices=[('S', 'Simples'), ('A', 'Intermediária'), ('B', 'Completa'), ('C', 'Grande porte'), ('D', 'Reforma')], max_length=1),
        ),
        migrations.AddField(
            model_name='historicalativo',
            name='ultima_prev_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalativo',
            name='ultima_prev_medicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalchecklistatividade',
            name='carregado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalchecklistatividade',
            name='id_checklist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalchecklistatividade',
            name='id_externo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalchecklistatividade',
            name='nome_checklist',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='historicalchecklistatividade',
            name='origem_arquivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='historicalchecklistatividade',
            name='seq',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalitemmaterial',
            name='carregado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalitemmaterial',
            name='codigo_fabricante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalitemmaterial',
            name='fornecedor_principal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalitemmaterial',
            name='id_externo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalitemmaterial',
            name='origem_arquivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='historicalitemmaterial',
            name='subtipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpessoa',
            name='carregado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpessoa',
            name='horas_contratuais_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='historicalpessoa',
            name='id_externo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalpessoa',
            name='origem_arquivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='historicalpessoa',
            name='setor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.setor'),
        ),
        migrations.AddField(
            model_name='historicalpessoa',
            name='tipo_mo',
            field=models.CharField(blank=True, help_text='Classificação de mão de obra do importador (tipo_mo).', max_length=100),
        ),
        migrations.AddField(
            model_name='itemmaterial',
            name='carregado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemmaterial',
            name='codigo_fabricante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itemmaterial',
            name='fornecedor_principal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='itemmaterial',
            name='id_externo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemmaterial',
            name='origem_arquivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='itemmaterial',
            name='subtipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='carregado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='horas_contratuais_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='id_externo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='origem_arquivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas', to='core.setor'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo_mo',
            field=models.CharField(blank=True, help_text='Classificação de mão de obra do importador (tipo_mo).', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='ativo',
            unique_together={('organizacao', 'id_externo')},
        ),
        migrations.AlterUniqueTogether(
            name='checklistatividade',
            unique_together={('organizacao', 'id_externo')},
        ),
        migrations.AlterUniqueTogether(
            name='itemmaterial',
            unique_together={('organizacao', 'id_externo')},
        ),
        migrations.AlterUniqueTogether(
            name='pessoa',
            unique_together={('organizacao', 'id_externo')},
        ),
    ]
