# Generated by Django 6.0.7 on 2026-07-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_checklistatividade_options_ativo_carregado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistatividade',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalchecklistatividade',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalitemmaterial',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemmaterial',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
