# Generated by Django 6.0.7 on 2026-07-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_checklistatividade_observacao_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklistatividade',
            unique_together={('organizacao', 'id_checklist', 'id_externo')},
        ),
    ]
