# Generated by Django 6.0.7 on 2026-07-16 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo_os', models.CharField(max_length=100)),
                ('sistema_falha', models.CharField(blank=True, max_length=200)),
                ('descricao_falha', models.TextField(blank=True)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hh_executadas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('horimetro', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('origem_arquivo', models.CharField(blank=True, max_length=300)),
                ('carregado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='cadastro.ativo')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='cadastro.oficina')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organizacao')),
            ],
            options={
                'verbose_name': 'Ordem de serviço',
                'verbose_name_plural': 'Ordens de serviço',
                'ordering': ['-data'],
            },
        ),
    ]
