# Generated by Django 6.0.7 on 2026-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('importacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='custo_hh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='custo_pecas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='id_externo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='mecanico_responsavel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='carregado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateField(help_text='data_abertura no importador'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='horimetro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='medicao_na_os', max_digits=12, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ordemservico',
            unique_together={('organizacao', 'id_externo')},
        ),
    ]
